language: android
android:
    components:
        - build-tools-23.0.1
        - android-21
before_script:
    - chmod +x gradlew
script:
    - ./gradlew assembleDebug assembleRelease check
after_success:
    - ./gradlew jacocoTestReport coveralls