language: android
android:
    components:
        - tools
        - build-tools-23.0.3
        - android-23
        - extra-android-m2repository
before_script:
    - chmod +x gradlew
script:
    - ./gradlew assembleDebug assembleRelease check
after_success:
    - ./gradlew jacocoTestReport coveralls
after_failure:
    - cat awex-android/build/outputs/lint-results-*.html